[system]
username = "penguin"
hostname = "linux"
timezone = "Europe/Lisbon"
locale = "en_US.UTF-8"
keymap = "pt-latin1"
state = "25.11"

[devel]
name = "Gonçalo Oliveira"
email = "goncalo.oliveira@tuta.com"

[devel.github]
auth = "~/.ssh/github_auth"
sign = "~/.ssh/github_sign.pub"
