[general]
name = "Gonçalo Oliveira"
email = "goncalo.oliveira@tuta.com"

[system]
username = "penguin"
hostname = "linux"
timezone = "Europe/Lisbon"
locale = "en_US.UTF-8"
state = "25.11"

[system.keymap]
console = "pt-latin1"
graphical = "pt"

[theme]
accent = "flamingo"
flavor = "mocha"

[devel.github]
auth = "~/.ssh/github_auth"
sign = "~/.ssh/github_sign.pub"
